uber-web/probe.gl

- src/test-utils/browser-automation/browser-test-driver.js
need server to debug code when test fails
> not stop server when test fails

- src/lib/log.js
- src/test-utils/browser-automation/browser-driver.js
- src/test-utils/browser-automation/browser-test-driver.js
- Add server setup retry logic
- Fix a bug in log
- Use log to print message to console
> Improve browser test with server setup retry logic

- CHANGELOG.md
- package.json
- yarn.lock
> Remove asciify-image as a dependency

- docs/api-reference/log/log.md
- docs/whats-new.md
- src/lib/log.js
- src/lib/utils/assert.js
- test/src/lib/log.spec.js
For https://github.com/uber/luma.gl/issues/727
- add APIs
- add test cases
- update document
> add APIs to control the debug settings

- docs/api-reference/test-utils/browser-test-driver.md
- package.json
- src/test-utils/browser-automation/browser-driver.js
- src/test-utils/browser-automation/browser-test-driver.js
- src/test-utils/browser-automation/call-exposed-function.js
- test/start.js
- test/test-browser-auto.js
- test/test-browser-headless.js
- test/webpack.config.js
You can see the browser tests successfully run on Travis CI for this PR.
Much of this setup should definitely go into ocular-dev-tools instead of duplicated across repos.
> Run browser test in headless mode

- docs/api-reference/log/log.md
- test/src/lib/log.spec.js
#38 
- update API names in docs and unit test
> update API names and docs in Log class

- docs/api-reference/test-utils/log-to-dom.md
- modules/core/src/index.js
- modules/test-utils/src/index.js
- modules/test-utils/src/utils/log-to-dom.js
- test/test-browser.js
> Move logToDOM to test-utils

- test/bench/browser.js
- test/bench/index.js
- test/start.js
> Fix bench tests

- modules/bench/src/bench.js
- modules/bench/src/stat-utils.js
- test/modules/bench/index.js
- test/modules/bench/stat-utils.spec.js
- Run each test function at least once before benchmarking (exclude JIT compiling time)
- Run each test multiple times and report relative standard error
> Bench module improvements

- modules/bench/src/bench-loggers.js
- modules/bench/src/bench.js
- modules/bench/src/index.js
Prep diff for benchmarking of async methods.
> Bench code simplification (PR#1 of 2)

- test/modules/core/lib/index.js
- test/modules/core/lib/utils.spec.js
Adding tests for the new `getHiResTimers` function.
> Add test for getHiResTimer

- modules/stats-widget/src/stats-widget.js
Support for rendering widget before stats fields are fully populated.
> Fix dynamic dom creation

- CHANGELOG.md
- package.json
- test/browser.js
- test/index.js
- test/modules/core/lib/log.spec.js
- test/modules/core/lib/raw-logging.js
- yarn.lock
Probe tests and builds seem broken, attempting to fix
> Bump ocular-dev-tools@0.0.19

- modules/test-utils/src/browser-automation/browser-driver.js
Log error message and quit testing if webpack-dev-server logs to stderr.
> Improve BrowserDriver error handling

- modules/test-utils/package.json
- modules/test-utils/src/browser-automation/browser-test-driver.js
- yarn.lock
- Fix problematic page injection
- Remove version lock for puppeteer
> [BrowserDriver] fix crash on newer chromium versions

- .travis.yml
- package.json
- yarn.lock
This change avoids installing a local copy of Chromium
> Upgrade ocular-dev-tools

- docs/api-reference/test-utils/browser-test-driver.md
- modules/test-utils/src/browser-automation/browser-test-driver.js
- modules/test-utils/src/utils/puppeteer-events.js
> [test-utils] BrowserTestDriver: expose an API for keyboard/mouse input

- docs/README.md
- docs/api-reference/log/stats.md
- docs/table-of-contents.json
- docs/whats-new.md
- lerna.json
- modules/bench/README.md
- modules/core/README.md
- modules/stats-widget/README.md
- modules/test-utils/README.md
- website/package.json
- Will publish 3.1-beta.1
- Updates website to ocular-gatsby@1.0
@jckr - so many warnings on the gatsby website during both build and in the console during runtime, any chance you could take a quick look?
> 3.1-beta prep

- modules/bench/src/bench.js
Addresses the old TODO on now [deleted line 278](https://github.com/uber-web/probe.gl/compare/ib/single-code-path?expand=1#diff-f3ea11566bdcefa2b6c26d2c8a52c7f2L278).
This is a prep diff for a small feature PR.
> bench: Join sync and async runner code paths

- examples/browser-test/package.json
- examples/stats-widget/package.json
- make example private. skip lerna publish
Signed-off-by: Shan He <heshan0131@gmail.com>
> make example private

- extensions/seer/README.md
> Update Seer images

- modules/log/src/index.ts
- modules/log/src/utils/autobind.ts
- modules/log/src/utils/color.ts
- modules/log/src/utils/formatters.ts
- modules/log/src/utils/hi-res-timestamp.ts
- modules/log/src/utils/local-storage.ts
- package.json
- Runs the typescript compiler and generates .d.ts files
> feat: Enable .d.ts builds

- modules/test-utils/src/browser-automation/browser-driver.ts
For https://github.com/visgl/loaders.gl/pull/1940
> fix(test-utils): Disable puppeteer timeout

- modules/log/package.json
- modules/log/src/log.ts
- modules/log/src/node/node-asciify-image.ts
- yarn.lock
https://github.com/uber-web/probe.gl/issues/196
> fix(log): "quarantine" dynamic import of asciify-image

- .prettierignore
- examples/benchmarks/app.tsx
- examples/stats-widget/app.tsx
- modules/bench/src/bench-loggers.ts
- modules/bench/src/bench.ts
- modules/env/src/lib/is-electron.ts
- modules/log/src/index.ts
- modules/log/src/log.ts
- modules/log/src/utils/local-storage.ts
- modules/react-bench/src/components/bench-results.tsx
- modules/seer/src/api.ts
- modules/stats-widget/src/stats-widget.ts
- modules/test-utils/src/browser-automation/browser-driver.ts
- package.json
- test/bench/browser.ts
- test/bench/index.ts
- test/browser.js
- tsconfig.json
Gradually enabling all options in tsconfig.json
> chore: stricter typescript settings

- modules/bench/src/bench.ts
- modules/bench/tsconfig.json
- modules/log/src/log.ts
- modules/log/tsconfig.json
Follow-up to #219 . Handles bench and log modules
> chore(bench): Enable all typescript checks on `bench` module

- modules/test-utils/src/browser-automation/browser-driver.ts
- modules/test-utils/src/browser-automation/browser-test-driver.ts
Add an optional callback to start the server
> feat(test-utils) BrowserDriver support custom server implementation

- modules/env/src/lib/is-browser.ts
> fix(env): Fix regression in isBrowser() check
