uber-web/probe.gl

src/lib/log.js

Skip calling `_getElapsedTime` etc. if the current priority is disabled.

Do not parse arguments if log is disabled by priority

---

docs/api-reference/test-utils/browser-test-driver.md
src/test-utils/browser-automation/browser-test-driver.js
src/test-utils/image-utils/diff-images.js

- New exposed function `browserTestDriver_isHeadless()` for detecting the test environment from the web app. This is needed to adjust pixel matching tolerance when under headless mode.
- Add `saveOnFail` option to `browserTestDriver_captureAndDiffScreen`.

Add APIs for saving screenshot to disk

---

docs/api-reference/test-utils/browser-test-driver.md
modules/test-utils/src/browser-automation/browser-test-driver.js

`browserTestDriver_isHeadless` was an async function which is cumbersome to use.
With this change, `browserTestDriver_isHeadless` is a function if in headless mode, and `undefined` otherwise.

Simplify isHeadless global

---

modules/test-utils/src/browser-automation/browser-test-driver.js
modules/test-utils/src/utils/diff-images.js

Improve error handling in the following cases:
- Golden image size does not match screenshot
- Golden image cannot be loaded

Fix: saveOnFail does not work if an error is thrown

---

.eslintrc
modules/bench/src/bench.js
modules/bench/src/timer.js

I noticed `Date` is used for timing in the benchmarks, which will lose sub-millisecond measurements. This update will get the best timer available for the platform: `performance` in the browser, `hrtime` in node, fallback to `Date` in other cases.

Hi-res timer for benchmarks

---

.eslintrc
.gitignore
.travis.yml
aliases.js
docs/api-reference/bench/bench.md
docs/whats-new.md
modules/bench/src/bench.js
package.json
test/bench/index.js
test/modules/bench/bench.spec.js
test/modules/bench/iterator.bench.js
test/start.js
test/test-browser.js
test/webpack.config.js
yarn.lock

- Just adds a new `Bench.addAsync` method that will track a promise.
- Needed for development of "streaming" support in loaders.gl.

Add support for async benchmarks (PR#2 of 2)

---

.eslintrc
docs/api-reference/log/stats.md
docs/api-reference/stats-widget/stats-widget.md
modules/core/src/lib/stat.js
modules/core/src/lib/stats.js
modules/stats-widget/src/stats-widget.js

- Restored `stats.getTable()` method to format stats suitably for `console.table`
- Created default formatters that can be indicated by name, e.g. "averageTime", "memory", "fps"
- Replaced canvas-based rendering with DOM. Simplifies the code a lot and allows for CSS to be fully customized
- `framesPerUpdate` option allows app to just call `update` each frame. Throttling is handled internally
- Per-stat `resetOnUpdate` option indicates that a stat should be reset every time the widget is re-rendered (i.e. every `framesPerUpdate` frames)
- `title` option can replace the `stats.id` as the widget's header
- Enabled eslint on `StatsWidget`
Putting that all together, the API looks like this:
```js
const statsWidget = new StatsWidget(this.stats, {
title: 'Render Time',
framesPerUpdate: 60,
css: …
```

More stats updates

---

docs/api-reference/log/stat.md
modules/core/src/lib/stat.js
test/modules/core/lib/stats.spec.js

Update `Stat` class to be able to track a "sample window". Also separate `samples` from `count` to allow for similar tracking of count metrics. New methods:
- `setSampleSize`: set the size of the sample window
- `getAverageCount`: get average count/sample over all samples
- `getSampleAverageTime`: get average time/sample in the last sample window
- `getSampleAverageCount`: get average count/sample in the last sample window
- `getSampleHz`: get average number of samples/second in the last sample window

Sample window

---

modules/core/src/lib/stat.js
modules/core/test/lib/stats.spec.js

For https://github.com/uber/deck.gl/issues/3633
fix typo when updating `lastTiming`

Fix stat object typo lastTiming

---

modules/core/src/lib/log.js
modules/core/test/lib/log.spec.js

The rest parameters syntax is not supported in IE.
After transpilation, it looks like this:  https://unpkg.com/browse/probe.gl@3.1.1/dist/es6/lib/log.js#L138
This operation is performed regardless of whether logging is enabled.
This PR moves the construction of `args` array into `normalizeArguments`.

Remove rest parameters from Log class

---

docs/api-reference/log/log.md
modules/core/src/lib/log.js
modules/core/test/lib/log.spec.js

Follow up of discussion on https://github.com/uber/deck.gl/pull/3957#discussion_r354040744

Rename log.priority to log.level

---

docs/api-reference/log/log.md
modules/core/src/lib/log.js
modules/core/test/lib/log.spec.js

Follow up of discussion on https://github.com/uber/deck.gl/pull/3957#discussion_r354040744
No breaking change - `priority` is still supported.

Rename `log.priority` to `log.level`

---

docs/api-reference/log/log.md
modules/core/src/lib/log.js

- If log is disabled, all levels of logging are expected to be blocked. Currently it doesn't block L0 including warnings, errors and level=0 logs. The `enabled` flag is practically meaningless (can just be replaced with `log.level = 0`).
- It's reasonable to expect that `new Log().log('hello')()` would actually log something to the console. Currently log instances are disabled by default.
- It's cumbersome for the users to have to do `log.enable(true).setLevel(1)` just to see some logs.
In both deck.gl and luma.gl, the log objects are enabled on initialization, e.g. https://github.com/uber/deck.gl/blob/7.3-release/modules/core/src/utils/log.js#L3
Therefore changing the default here does not affect the default behavior in our primary use cases.

Change default `enabled` behavior of Log class

---

docs/api-reference/bench/bench.md
docs/whats-new.md
modules/bench/src/bench.js
modules/bench/src/format-utils.js
modules/bench/test/bench.spec.js
modules/bench/test/iterator.bench.js
modules/bench/test/parse-color.bench.js

When measuring e.g. iteration speed, the actual number of iterations is a multiple of the reported number.
The addition of this options allows the reporting to reflect the real number of iterations, making different results more meaningful and comparable:
```
const LENGTH = 1e6;
bench.add('for (let i=0; ...)', {repetitions: LENGTH}, () => {
let sum = 0;
for (let i = 0; i < LENGTH; i++) {
sum += i;
}
return sum;
})
```

bench: Add `options.repetitions` to tests for more meaningful metrics reporting

---

docs/api-reference/test-utils/browser-test-driver.md
modules/test-utils/package.json
modules/test-utils/polyfill.js

`require('@probe.gl/test-utils/polyfill');` in the client script allows it to run in non-puppeteer environments.

[test-utils] Add polyfill

---

modules/test-utils/polyfill.js

`browserTestDriver_isHeadless` should only be present in the headless mode.

Remove isHeadless from polyfill

---

modules/stats-widget/src/stats-widget.ts

Indicates the header is an interactable (collapse/uncollapse) element.

Stats widget: Header should have `pointer` cursor

---

modules/log/src/log.ts
modules/log/src/utils/assert.ts

Use [special syntax](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#assertion-functions) for `Log.assert` so Typescript can properly deduce type of variable if `assert` doesn't throw.
See this discussion: https://github.com/visgl/deck.gl/pull/6659#discussion_r810002439

feat(log): More robust typings for log.assert.

---

modules/bench/src/bench.ts

`bench.opts.id`, which defaults to empty string, should not overwrite `test.id`.

fix(bench) Fix logging

---

modules/stats-widget/src/stats-widget.ts
modules/stats-widget/test/stats-widget.spec.js

Fix the following issues:
- StatsWidget permanently modifies the CSS styles of user-supplied container
- When no container is specified, StatsWidget creates a container that is not removed upon calling `remove()`
These cause render tests to fail because `StatsWidget` instances created during unit tests do not clean up after themselves.

Fix StatsWidget test

---

modules/bench/src/format-utils.ts
modules/bench/src/stat-utils.ts
modules/env/src/lib/get-browser.ts
modules/env/src/lib/globals.ts
modules/log/src/log.ts
modules/log/src/utils/hi-res-timestamp.ts
modules/log/src/utils/local-storage.ts
modules/react-bench/tsconfig.json
modules/stats-widget/src/stats-widget.ts
modules/stats-widget/test/stats-widget.spec.js
modules/stats-widget/tsconfig.json
modules/stats/src/lib/stat.ts
modules/stats/src/lib/stats.ts
modules/stats/tsconfig.json
modules/test-utils/src/utils/log-to-dom.ts
test/bench/browser.ts
tsconfig.json

- `log`, `bench` and `test-utils` modules need more work (due to complex overloading or puppeteer related typing issues), other modules are now fully checked.

chore: Enable all available typescript checks to selected modules

---

modules/env/src/lib/globals.ts

Vite with node polyfill throws "Identifier process is already defined"

Fix globals bundle error

---

babel.config.cjs

Add [setPublicClassFields](https://babeljs.io/docs/assumptions#setpublicclassfields) and [setClassMethods](https://babeljs.io/docs/assumptions#setclassmethods) to babel assumptions. Significantly reduces the verbosity of the output.
After this change, the ESM entry points technically no longer need `@babel/runtime`. I left the dependency in package JSONs since `transform-runtime` is still used for transpile to ESM, in case some other references pop up later with an unintentional change.

Update babel config

---

.github/workflows/test.yml
examples/benchmarks/package.json
examples/browser-test-vite-wip/package.json
examples/stats-widget/package.json
lerna.json
modules/test-utils/package.json
modules/test-utils/src/browser-automation/browser-driver.ts
modules/test-utils/src/browser-automation/browser-test-driver.ts
package.json
yarn.lock

- Require a more recent version of puppeteer; make puppeteer an optional peer dependency
- BrowserDriver types clean up

[test-utils] Upgrade puppeteer
